import { ModalCode } from "./types"

export const BACKEND_URL = import.meta.env.VITE_BACKEND_URL

export const BACK_URL = import.meta.env.VITE_BACKEND_URL_FASTIFY

export const modalCodes: Record<ModalCode, ModalCode> = {
  MODAL_USER_SIGNIN: "MODAL_USER_SIGNIN",
  MODAL_USER_REGISTRATION: "MODAL_USER_REGISTRATION",
  MODAL_FORGOT_PASSWORD: "MODAL_FORGOT_PASSWORD",
  MODAL_EMAIL_ALREADY_EXISTS: "MODAL_EMAIL_ALREADY_EXISTS",
  MODAL_ACCOUNT_CREATION_SUCCESSFUL: "MODAL_ACCOUNT_CREATION_SUCCESSFUL",
  MODAL_CREATE_WISHLIST: "MODAL_CREATE_WISHLIST",
  MODAL_CLOSE: "MODAL_CLOSE"
}
